server:
  port: 80

spring:
  config:
    import:
      - classpath:/app/jwt/jwt.yml
      - classpath:/app/cors/cors.yml
      - classpath:/app/upload/upload-image.yml
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_DB_JDBC_URL:jdbc:postgresql://localhost:5432/joara_postgres}
    username: ${POSTGRES_DB_USERNAME:root}
    password: ${POSTGRES_DB_PASSWORD:root}
  jpa:
    #    hibernate:
    #      ddl-auto: validate # or none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration
    schemas: joara_basic
  sql:
    init:
      platform: postgres
